[package]
name = "egui_inspect_derive"
version = "0.2.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2", features = ["proc-macro"] }
proc-macro2 = "1"
darling = "0.21"
